# action.yml
name: 'Libreoffice Convert'
description: 'Run libreoffice commands in headless mode'
author: 'Juan Manuel Servera'
branding:
  icon: printer
  color: yellow
inputs:
  command:  # id of input
    description: 'The command to run'
    required: true
    default: 'libreoffice --headless --invisible --version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
